### ISSUE TITLE
HadCRUT4 Data: download url

### ISSUE THREAD

**Issue by ghost** [hrbrmstr/hadcrut#1]
Hi,

global_temp.r

http://www.metoffice.gov.uk/hadobs/hadcrut4/data/current/time_series/HadCRUT.4.4.0.0.monthly_ns_avg.txt

has changed to
http://www.metoffice.gov.uk/hadobs/hadcrut4/data/current/time_series/HadCRUT.4.5.0.0.monthly_ns_avg.txt

Greetings
Christof

**Comment by hrbrmstr** [comment]
thx. code updated.
